### ISSUE TITLE
conn.logout() --> error message adapter.log

### ISSUE THREAD

**Issue by fm0609** [ioBroker/ioBroker.socketio#146]
The adapter works fine. But disconnecting the socket doing **conn.logout()** triggers an error message in the ioBroker log and shutsdown the socket.io adapter, which automatically is doing a successfull restart.

Here are the logs:

<html>
<body>
<div class="MuiGrid-root-246 MuiGrid-container-247 MuiGrid-item-248 MuiGrid-align-items-xs-center-255" style="box-sizing: border-box; width: 1632px; display: flex; flex-wrap: wrap; margin: 0px; align-items: center; color: rgba(0, 0, 0, 0.87); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, &quot;Courier New&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="MuiBadge-root-106" title="Fehler anzeigen" style="box-sizing: inherit; display: inline-flex; position: relative; flex-shrink: 0; vertical-align: middle;"><span class="MuiBadge-badge-107 jss2120 jss2121 MuiBadge-anchorOriginTopRightRectangle-112 MuiBadge-colorError-110" style="box-sizing: border-box; height: 20px; display: flex; padding: 0px 6px; z-index: 1; position: absolute; flex-flow: row wrap; font-size: 0.75rem; min-width: 20px; transition: transform 225ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; align-items: center; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1; place-content: center; border-radius: 10px; color: rgb(255, 255, 255); background-color: rgb(244, 67, 54); top: 10px; right: 10px; transform: scale(1) translate(50%, -50%); transform-origin: 100% 0%;">88</span></span><span class="MuiBadge-root-106" title="Fehler und Warnungen anzeigen" style="box-sizing: inherit; display: inline-flex; position: relative; flex-shrink: 0; vertical-align: middle;"><button class="MuiButtonBase-root-85 MuiIconButton-root-77" tabindex="0" type="button" style="box-sizing: inherit; color: rgba(0, 0, 0, 0.54); border: 0px; cursor: pointer; margin: 0px; display: inline-flex; outline: 0px; padding: 12px; position: relative; align-items: center; user-select: none; border-radius: 50%; vertical-align: middle; justify-content: center; text-decoration: none; background-color: transparent; appearance: none; -webkit-tap-highlight-color: transparent; flex: 0 0 auto; overflow: visible; font-size: 1.5rem; text-align: center; transition: background-color 150ms cubic-bezier(0.4, 0, 0.2, 1) 0ms;"><span class="MuiIconButton-label-84" style="box-sizing: inherit; width: 24px; display: flex; align-items: inherit; justify-content: inherit;"><svg class="MuiSvgIcon-root-86" focusable="false" viewBox="0 0 24 24" aria-hidden="true"><path d="M1 21h22L12 2 1 21zm12-3h-2v-2h2v2zm0-4h-2v-4h2v4z"></path></svg></span><span class="MuiTouchRipple-root-150" style="box-sizing: inherit; inset: 0px; z-index: 0; overflow: hidden; position: absolute; border-radius: inherit; pointer-events: none;"></span></button><span class="MuiBadge-badge-107 jss2120 jss2122 MuiBadge-anchorOriginTopRightRectangle-112" style="box-sizing: border-box; height: 20px; display: flex; padding: 0px 6px; z-index: 1; position: absolute; flex-flow: row wrap; font-size: 0.75rem; min-width: 20px; transition: transform 225ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; align-items: center; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1; place-content: center; border-radius: 10px; top: 10px; right: 10px; transform: scale(1) translate(50%, -50%); transform-origin: 100% 0%; background-color: rgb(255, 193, 7);">7</span></span><div class="jss2109" style="box-sizing: inherit; flex-grow: 1;"></div><div style="box-sizing: inherit;"><button class="MuiButtonBase-root-85 MuiButton-root-2247 MuiButton-contained-2255 MuiButton-containedPrimary-2256" tabindex="0" type="button" style="box-sizing: border-box; color: rgb(255, 255, 255); border: 0px; cursor: pointer; margin: 0px; display: inline-flex; outline: 0px; padding: 6px 16px; position: relative; align-items: center; user-select: none; border-radius: 4px; vertical-align: middle; justify-content: center; text-decoration: none; background-color: rgb(51, 153, 204); appearance: none; -webkit-tap-highlight-color: transparent; font-size: 0.875rem; min-width: 64px; transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms, box-shadow 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms, border 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.75; letter-spacing: 0.02857em; text-transform: uppercase; box-shadow: rgba(0, 0, 0, 0.2) 0px 3px 1px -2px, rgba(0, 0, 0, 0.14) 0px 2px 2px 0px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;"><span class="MuiButton-label-2248" style="box-sizing: inherit; width: 188.719px; display: inherit; align-items: inherit; justify-content: inherit;"><span class="MuiButton-startIcon-2269 MuiButton-iconSizeMedium-2272" style="box-sizing: inherit; display: inherit; margin-left: -4px; margin-right: 8px;"><svg class="MuiSvgIcon-root-86" focusable="false" viewBox="0 0 24 24" aria-hidden="true"><path d="M19 12v7H5v-7H3v7c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2v-7h-2zm-6 .67l2.59-2.58L17 11.5l-5 5-5-5 1.41-1.41L11 12.67V3h2z"></path></svg></span>LOG HERUNTERLADEN</span><span class="MuiTouchRipple-root-150" style="box-sizing: inherit; inset: 0px; z-index: 0; overflow: hidden; position: absolute; border-radius: inherit; pointer-events: none;"></span></button></div><div class="jss2109" style="box-sizing: inherit; flex-grow: 1;"></div><p class="MuiTypography-root-199 jss2110 MuiTypography-body2-200" title="Geschätzte Größe" style="box-sizing: inherit; margin: 0px 1rem; font-size: 0.875rem; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 1.43; letter-spacing: 0.01071em;">Log-Größe:<span> </span><span class="jss2111" style="box-sizing: inherit; font-style: italic;">160.5 KB</span></p></div><div class="MuiGrid-root-246 jss2152 MuiGrid-item-248" style="box-sizing: border-box; margin: 0px; height: 953px; overflow: hidden; color: rgba(0, 0, 0, 0.87); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, &quot;Courier New&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="MuiTableContainer-root-2154 jss2087" style="box-sizing: inherit; width: 1632px; overflow-x: auto; height: 953px;">

socketio.0 | Zeit | silly | Nachricht
-- | -- | -- | --
socketio.0 | 2023-02-22 15:49:50.138 | info | ==> Connected system.user.admin from ::ffff:192.168.178.45
socketio.0 | 2023-02-22 15:49:42.801 | info | socket.io server listening on port 8084
socketio.0 | 2023-02-22 15:49:42.622 | info | starting. Version 4.2.0 in /opt/iobroker/node_modules/iobroker.socketio, node: v16.18.1, js-controller: 4.0.23
socketio.0 | 2023-02-22 15:49:10.070 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
socketio.0 | 2023-02-22 15:49:10.068 | info | terminating
socketio.0 | 2023-02-22 15:49:10.065 | info | <== Disconnect system.user.admin from ::ffff:192.168.178.45 Test-Con
socketio.0 | 2023-02-22 15:49:10.064 | info | terminating http server on port 8084
socketio.0 | 2023-02-22 15:49:10.034 | error | invalid id undefined
socketio.0 | 2023-02-22 15:49:10.033 | error | Error: invalid id undefined at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2973:17) at StateRedisClient.destroySession (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:1282:26) at Adapter.destroySession (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:8242:27) at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.socketio/lib/socket.js:1550:26) at Socket.emit (node:events:513:28) at Socket.emit (node:domain:489:12) at /opt/iobroker/node_modules/iobroker.socketio/node_modules/socket.io/lib/socket.js:531:14 at processTicksAndRejections (node:internal/process/task_queues:78:11)
socketio.0 | 2023-02-22 15:49:09.693 | error | unhandled promise rejection: invalid id undefined
socketio.0 | 2023-02-22 15:49:09.692 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
socketio.0 | 2023-02-22 15:48:46.916 | info | ==> Connected system.user.admin from ::ffff:192.168.178.45

</div></div>
</body>
</html>

**Comment by GermanBluefox** [comment]
Should be fixed
